### ISSUE TITLE
Set up wordpress installation

### ISSUE THREAD

**Issue by adrian-activate** [ActivateMedia/DCAF-Anti-Corruption#1]

**Comment by gianpaolom** [comment]
A new instance of latest WP is deployed on server 

**IP**: 139.162.237.26

**URL**: http://securitysectorintegrity.com/

**Site root**: `/var/www/securitysectorintegrity.com/`

You have to add an entry in your `hosts` file until  the domain is registered; `www` redirects 301 to naked domain.
I already added an account for @andreafalzetti 
Let me know if you need any other.
