### ISSUE TITLE
Install mega menu plugin

### ISSUE THREAD

**Issue by adrian-activate** [ActivateMedia/DCAF-Anti-Corruption#11]

**Comment by andreafalzetti** [comment]
UberMenu plugin installed

**Comment by andreafalzetti** [comment]
Try the menu configuration "The Works" as per the website https://wpmegamenu.com/flyout/

**Comment by bhavesh-activatemedia** [comment]
Configure the existing menu to look like the example above. Also add a second tier sub menu as per the original site map and menu structure in the CMS

**Comment by bhavesh-activatemedia** [comment]
@karinapriajina I've added images onto the 'About' section of the website. What do you think? We think its better without the images as there is no connection with the image and the title of the page. 

There are lots of ways to configure the menu. See here for a video tutorials page (http://sevenspark.com/docs/ubermenu-3/video-tutorials) should you want to play around with the settings or add images to the rest of the menu. If you want the images removed, let me know.

**Comment by karinapriajina** [comment]
Hi @bhavesh-activatemedia ! Yeah, I think you are right. It's better without the pictures

**Comment by bhavesh-activatemedia** [comment]
@karinapriajina Ive deleted the images

**Comment by karinapriajina** [comment]
Many thanks! :)
