### ISSUE TITLE
Set up Google Analytics

### ISSUE THREAD

**Issue by adrian-activate** [ActivateMedia/DCAF-Anti-Corruption#13]

**Comment by andreafalzetti** [comment]
I have created a property in the Activate analytics account, and I've added DCAF's Gmail address as Admin. I have also installed the google analytics WP plugin.

**Comment by andreafalzetti** [comment]
When we buy the domain and set the DNS, we need to verify the domain with google search console.

**Comment by andreafalzetti** [comment]
Done

**Comment by karinapriajina** [comment]
Can we release the web onto google? (forgive my provincial way of putting this). 
After that, since I can't close this issue, can someone close ti for me please? Many thanks!

**Comment by andreafalzetti** [comment]
@karinapriajina the URL has been submitted.
