### ISSUE TITLE
Make home photo bigger

### ISSUE THREAD

**Issue by andreafalzetti** [ActivateMedia/DCAF-Anti-Corruption#15]

**Comment by bhavesh-activatemedia** [comment]
Make full screen more or less. Requires css changes to make it look like this: https://edindemo.wordpress.com

**Comment by andreafalzetti** [comment]
Done

**Comment by andreafalzetti** [comment]
* I need to make sure the person is always displayed in the picture (media query).
* have the quote closer to the person

**Comment by karinapriajina** [comment]
I can't close this issue, can someone close ti for me please? Many thanks!
