### ISSUE TITLE
Photo optimisation

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Anti-Corruption#16]
Wordpress seems to modify photo quality when uploading. Photos don't look as sharp as they should on the homepage.

**Comment by andreafalzetti** [comment]
Hi @karinapriajina, I hope you're well. There is a plugin called **EWWW Image Optimizer** that reduces the quality of the photos to make them web friendly and the website faster. I have increased the jpg quality from 82/100 to 90/100 - this should improve the next uploaded photos - let me know.

**Comment by karinapriajina** [comment]
Hi @andreafalzetti ! Happy New Year!!! I'm good, thanks! My first day in the office today. How are you? Thank you. Does this mean I have to re-upload all the current images?

**Comment by andreafalzetti** [comment]
@karinapriajina once the image is processed, you can't undo it. The photos you have uploaded look good to me. Maybe you can try with one or two to see if it worth doing the effort. If you want, you can compromise a little bit with loading time of the pages and you can disable the plugin and upload the full quality image.

**Comment by karinapriajina** [comment]
We can try. It's weird that for a web design that relies entirely on HD photos they suddenly loose quality.........or is the ideal only possible for the template... Not happy with wordpress marketing...
