### ISSUE TITLE
Image Copyright

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Anti-Corruption#17]
Could someone please double-check and confirm that we are allowed to use these photos http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/

**Comment by bhavesh-activatemedia** [comment]
Add copyright at the bottom of every relevant page as per the government license page guidelines

**Comment by andreafalzetti** [comment]
Andrea to add Copyright custom field of Pages in the backend and at the bottom of the page in the frontend

**Comment by andreafalzetti** [comment]
Done 

@karinapriajina you have a new field in the backend, you can add whatever you like (plain text or hyperlinks)

![screen shot 2017-02-03 at 14 48 19](https://cloud.githubusercontent.com/assets/2318450/22595558/e0b41b12-ea1f-11e6-92f7-7f3805eb34ca.jpg)


it will display as the following:

![screen shot 2017-02-03 at 14 48 08](https://cloud.githubusercontent.com/assets/2318450/22595567/e890247a-ea1f-11e6-8865-c0fd09f780e9.jpg)

**Comment by karinapriajina** [comment]
Ok Great! Thanks!
