### ISSUE TITLE
home page grid

### ISSUE THREAD

**Issue by bhavesh-activatemedia** [ActivateMedia/DCAF-Anti-Corruption#22]
Comparing the homepage (http://securitysectorintegrity.com) with the template (https://edindemo.wordpress.com/) I think having intro text in the grid for each item will make the page look better. Is this something you didn't want for a reason?

**Comment by karinapriajina** [comment]
Yes. You may be right, but I decided not to have extra text. It makes things more simple which is exactly what we're aiming for here. Also, the is a structural reason. If you click on main items now the lead you to another grid of topics, therefore acting as a submenu. If I add text, that wouldn't work anymore.
