### ISSUE TITLE
Is there a way I can rearrange the order of the items within the subsections (front end)?

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Anti-Corruption#25]
For example, when you go to Security Sector Governance, I would like "About security sector governance" tile/tab/photo to appear first and the others to follow from left to right. I have looked on publication date possibility but that does not seem to be the thing that determines the order of the posts.

**Comment by andreafalzetti** [comment]
Andrea to do some research

**Comment by andreafalzetti** [comment]
@karinapriajina WordPress allows to both manually and automatically order items.

### Automatic option
I could easily specify the grid page to load the sub-pages in alphabetical order or by publish date.

### Manual option
> You can change the order that your pages are displayed by using the Order field of the Page Options module.
> 
> Let’s say you have three pages: About, Photos, Contact
> 
> If you wanted About to appear first, you’d need to do the following:
> 
> Go to Pages in your dashboard
> Find the page About and click the title.
> Locate the Page Options module to the left of the editor.
> Put the number 1 in the box for Order. This tells WordPress to display this page first on your site.
> Click the Update button.
> Repeat the process for your other pages, but use higher numbers for the Order field: 2, 3, etc. This tells WordPress to display these pages second and third on your blog.

Source: https://en.support.wordpress.com/pages/page-options/

**Comment by andreafalzetti** [comment]
Please let me know which option you prefer.

**Comment by karinapriajina** [comment]
Hi @andreafalzetti !!! Thank you! i prefer the publishing date option as I am already familiar with it :)

I will sort the publishing dates of the concerned posts later today so when you implement the option the order is reflected.

Sorry for the delay in my responses!

**Comment by andreafalzetti** [comment]
I have done the change at my end

**Comment by karinapriajina** [comment]
Thank you @andreafalzetti !
