### ISSUE TITLE
Search Listing

### ISSUE THREAD

**Issue by andreafalzetti** [ActivateMedia/DCAF-Anti-Corruption#28]

**Comment by andreafalzetti** [comment]
@karinapriajina this is done, please have a look when you have some time and let me know if you are happy with the look of the search results page.

**Comment by karinapriajina** [comment]
Hi @andreafalzetti ! Yes, it looks great, thank you!

**Comment by karinapriajina** [comment]
I can't close this issue, can someone close ti for me please? Many thanks!
