### ISSUE TITLE
Footer : Navigation

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Anti-Corruption#29]
Dear all,

Just a quick note that this section is currently empty and it needs to be operational on the due day.

Many thanks!

**Comment by andreafalzetti** [comment]
Hi @karinapriajina, I have created a new menu named "Footer Navigation" in the backend, and placed it in the footer. Feel free to add or remove items from the menu, to display the pages you prefer, for the moment I have added Home, About, Contact us.

**Comment by karinapriajina** [comment]
Thank you! Will implement this evening

**Comment by karinapriajina** [comment]
Hi again @andreafalzetti , I can't seem to locate the footer navigation menu... can you please tell me where to find it? Or maybe if you have a moment, if you could add the following items to it that would help me out a lot: 

Publications
BI tools
Topics (we can skip topics if they don't fit all)

Many thanks!!! 

Karina

BWT, while looking for this I stumbled upon an issue in the main menu, I have created an issue for it.

**Comment by bhavesh-activatemedia** [comment]
@karinapriajina Appearance > menu > Near the top of the page 'select a menu to edit:' (choose footer navigation on dropdown).

I've added Publications and BI tools. Adding the Topics would make the menu increase in length when compared to the height of the map and address. What would you like to do?

**Comment by karinapriajina** [comment]
Hi @bhavesh-activatemedia ! Thank you that's wonderful! We can leave topics out, doesn't make too much sense adding them anyway.
