### ISSUE TITLE
Create site map

### ISSUE THREAD

**Issue by adrian-activate** [ActivateMedia/DCAF-Anti-Corruption#3]

**Comment by karinapriajina** [comment]
DOMAIN: www.securitysectorintegrity.com  
TITLE : SECURITY SECTOR INTEGRITY
SUBTITLE :  An Introduction to Building Integrity and Anti-Corruption in the Security Sector 
COLOR CODE: Content available in the Notes / Content available on the Ukraine Web

**MENU**

Home

About
• This Website
• DCAF
• BI Project

Publications

BI Tools

Topics
1.  Building Integrity 
   a.  About BI
   b.  Corruption
   c.  Anti-Corruption 
   d.  Building integrity and gender
2.  Security Sector Governance
   a.  About SSG
   b.  Security Sector Reform
   c.  Accountability 
   d.  Transparency 
   e.  Oversight 
3.  Defence Management
   a.  About DM
   b.  Policy
   c.  Planning
   d.  Programme Based Force Development
   e.  Resource Management (Budgeting)
   f.  Human Resources Management
   g.  Acquisition 
   h.  Procurement
4.  Standards and Regulations
   a.  International Standards
   b.  Regulatory Frameworks
   c.  Codes of Conduct
   d.  Integrity Pacts
   e.  Whistleblowing
   f.  Offset Arrangements
   g.  Audit(ing)
   h.  Procurement Monitoring & Evaluation
   i.  Missions and Operations
   j.  Security Sector Legislation
5.  Institutions and Organisations
   a.  National BI Approaches
   b.  NATO and BI
   c.  International Organisations
   d.  Security sector 
   e.  Defence 
   f.  Intelligence
   g.  Police/Law Enforcement
   h.  The role of Government
   i.  The role of Parliament
   j.  Parliamentary Oversight
   k.  Ombudsman Institutions
   l.  (Oversight) role of civil society ( and Media)
6.  Best Practices

Contact

**Comment by andreafalzetti** [comment]
I have created all the top level pages and some of the subpages. I have also set up the main menu accordingly.

**Comment by karinapriajina** [comment]
Home
About
•	This Website
•	DCAF
•	BI Project
Publications
BI Tools
Topics
1)	Building Integrity 
1.	About BI
2.	Corruption
3.	Anti-Corruption 

2)	Security Sector Governance
1.	About SSG
2.	Security Sector Reform
3.	SSG Institutions
1.	Security sector 
2.	Defence 
3.	Intelligence
4.	Police/Law Enforcement
5.	The role of Government
6.	The role of Parliament
7.	Parliamentary Oversight
8.	Ombudsman Institutions
9.	(Oversight) role of civil society ( and Media)
4.	Accountability 
5.	Transparency 
6.	Oversight 

3)	Defence Management
1.	About DM
2.	Policy
3.	Planning
4.	Programme Based Force Development
5.	Resource Management (Budgeting)
6.	Human Resources Management
7.	Building integrity and gender
8.	Acquisition 
9.	Procurement

4)	Standards and Regulations
1.	International Standards
2.	Regulatory Frameworks
3.	Codes of Conduct
4.	Integrity Pacts
5.	Whistleblowing
6.	Offset Arrangements
7.	Audit(ing)
8.	Procurement Monitoring & Evaluation
9.	Missions and Operations
10.	Security Sector Legislation

5)	Institutions and Organisations
1.	National BI Approaches
2.	NATO and BI
3.	International Organisations

6)	Best Practices (a list of recommendations)
Contact

**Comment by karinapriajina** [comment]
[BI WEB STRUCTURE latest.docx](https://github.com/ActivateMedia/DCAF-Anti-Corruption/files/621624/BI.WEB.STRUCTURE.latest.docx)
