### ISSUE TITLE
Publications template

### ISSUE THREAD

**Issue by bhavesh-activatemedia** [ActivateMedia/DCAF-Anti-Corruption#30]
Pages are not full width ie: http://securitysectorintegrity.com/publication/legislating-security-sector-toolkit-strengthening-financial-oversight-security-sector/

As there is no 'page attributes' for publications as per the other pages, I presume this has to be changed on the 'template for publications'?

**Comment by andreafalzetti** [comment]
This issue has been fixed. 

Example:
http://securitysectorintegrity.com/publication/building-integrity-key-issues-concepts/

![screen shot 2017-04-26 at 10 54 35](https://cloud.githubusercontent.com/assets/2318450/25428797/c67008da-2a6e-11e7-9346-e25fd0fb2f0a.jpg)

**Comment by karinapriajina** [comment]
Many thanks! (again, can't close this)
