### ISSUE TITLE
Publications Listing

### ISSUE THREAD

**Issue by bhavesh-activatemedia** [ActivateMedia/DCAF-Anti-Corruption#31]
![img_5943](https://cloud.githubusercontent.com/assets/5073275/22642692/b2500e26-ec53-11e6-85a5-29bb625ccae3.PNG)

**Comment by andreafalzetti** [comment]
This issue has been fixed. 

Example:
http://securitysectorintegrity.com/publication/building-integrity-key-issues-concepts/

![screen shot 2017-04-26 at 10 54 35](https://cloud.githubusercontent.com/assets/2318450/25428797/c67008da-2a6e-11e7-9346-e25fd0fb2f0a.jpg)

**Comment by andreafalzetti** [comment]
This issue has been fixed. 

![](http://i.imgur.com/e5L3vpa.jpg)

![](http://i.imgur.com/xdbcbxu.jpg)

**Comment by karinapriajina** [comment]
Looks fine to me now. Many thanks! (can't close this myself)
