### ISSUE TITLE
social share (facebook --> issue)

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Anti-Corruption#33]
![image](https://cloud.githubusercontent.com/assets/15872221/22710492/cdb8c222-ed7d-11e6-898d-bca4b9551326.png)

**Comment by andreafalzetti** [comment]
@karinapriajina can you clean the cache of your browser and try again? I have fixed that last week and I just tried sharing a publication and it worked. Please let me know if it works

![screen shot 2017-02-07 at 21 02 44](https://cloud.githubusercontent.com/assets/2318450/22711361/d4ad7eb0-ed78-11e6-8a51-4cd4a975f70a.jpg)

**Comment by karinapriajina** [comment]
Hi @andreafalzetti ! Thanks a lot! I'm not sure I know how to do that. But if you tell me that it works I trust you!

**Comment by bhavesh-activatemedia** [comment]
I clicked on the share buttons and its works for me
