### ISSUE TITLE
Text formatting options missing from back end

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Anti-Corruption#34]
I believe this may have occurred when the "copyright" field was added at the back end. Some text formatting options have disappeared from the back end, such as "justified" text and "font size"... I use the first one quite a lot and I need it to unify text formatting across the website.

I do believe they were there at the beginning, ... right?

**Comment by andreafalzetti** [comment]
Hi @karinapriajina, it seems working fine on my machine. Can you see the following?

![screen shot 2017-02-07 at 20 49 49](https://cloud.githubusercontent.com/assets/2318450/22710921/193d21ae-ed77-11e6-9d24-4110d7b8e0cb.jpg)

**Comment by karinapriajina** [comment]
Hi @andreafalzetti ! What I am missing in there is this:
![image](https://cloud.githubusercontent.com/assets/15872221/22732022/013e81da-eded-11e6-8227-c629d2ecf7e3.png)

**Comment by andreafalzetti** [comment]
On which website are you seeing that? I don't think it exists by default in WordPress so maybe we need a plugin for that.

**Comment by karinapriajina** [comment]
That was word, it was just to explain what option I was referring to. I know it was there before because I have used it in the beginning to format the topics. It is also in the back end of the ukraine website.... 
The text in topics etc is ideally full length on the front end and that requires the "justiified" option on the back end. Since some content was copied from the ukraine web and some from word documents the formatting through out it is not always consistent...which is not a huge problem...but it would be nice to have the option of correcting it.

**Comment by andreafalzetti** [comment]
@karinapriajina I am not sure where you have seen that in the Ukrainian site, I checked twice and I can't see it. I am also sure that justify doesn't exist because it's not a web-friendly thing, it's more used on paper but I understand it sometimes can be useful. I have installed a plugin that extends the functionalities of the text editor. I have already added the justify button, but there are a bunch more, if you want to look into them I leave you a link:

http://securitysectorintegrity.com/wp-admin/options-general.php?page=tinymce-advanced

**Comment by andreafalzetti** [comment]
mystery solved @karinapriajina ! You were right, it was there before WordPress 4.7!! Sorry :)

> The underline and justify buttons are no longer available. According to Andrew Ozz, who primarily works on the TinyMCE editor in WordPress, underlining text causes confusion as readers may interpret it as a link. The justify button was removed because it has uneven browser implementation and often makes text less readable. However, keyboard shortcuts for both buttons will continue to work in 4.7.

Source: https://wptavern.com/wordpress-4-7-removes-the-underline-and-justify-buttons-from-the-editor

**Comment by karinapriajina** [comment]
Awesome! I was beginning to think there for a second that I was seeing things, haha!
Ok, we'll just have to accept the change then....

**Comment by karinapriajina** [comment]
Thank you for the button! I think that will be enough. :)
