### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Anti-Corruption#36]
Dear all,

I hope you are well!
Question: would it be possible to install the necessary for a Ukrainian and a Russian translations of the site? How much time /cost would this represent?

Kind regards,

K

**Comment by andreafalzetti** [comment]
@karinapriajina A basic setup of the WPML plugin could take from a couple of hours to  a day depending on how many things you want us to setup. 

In a couple of hours, we can install the plugin, set the general configuration, add both languages and allow admin only to see the new languages.

If we need to create translations for the different pages, sync menus, create new widgets for the other languages, etc, etc, this could take up to a day.

**Comment by karinapriajina** [comment]
Dear Andrea,

Thank you very much! Please go ahead for the setup of ukrainian and russian languages. If you are running out of quartely allowed time please let me know. There's no rush on this for the moment so if you can squeeze this into maintenance that would be great. We will certainly end up needing more time than the quater allows later on but for now things can be done with calm. Please remind me, how much would a day of your work outside the maintenance contract cost? Many thanks. 

PS: our dear friend Viktor should be in charge of upload, however, this is still to be confirmed.

**Comment by karinapriajina** [comment]
Hold that thought on Viktor, apparently he's unavailable

**Comment by karinapriajina** [comment]
Dear Andrea, 
I hope you are well! have you been able to enable the above mentioned languages? I will need you to please create an admin access for the translator of Ukrainian and Russian versions, I do not have the person's name yet so we can use something generic for the username such as "Translator"

I would ideally need this information beginning of next week. Thank you very much in advance.

Kind regards,

Karina

**Comment by andreafalzetti** [comment]
@karinapriajina The Russian language is enabled and the site is ready to be translated. I have created an account as requested, I will forward you the login credentials.

**Comment by karinapriajina** [comment]
Hi Andrea! Thank you very much! Would it be possible to also enable the Ukrainian language too? PS: I don't have slack anymore. Changed computers, I could install again but not today and may need to sort with IT...

**Comment by andreafalzetti** [comment]
@karinapriajina - No problem, I will email you the password then. It was for security reasons so I recommend resetting the password once you receive it.

Both Ukrainian and Russians are enabled! Thanks

**Comment by karinapriajina** [comment]
Question: http://securitysectorintegrity.com/wp-admin/edit.php?post_type=publication
How do I translate a publication?

**Comment by andreafalzetti** [comment]
try now

**Comment by karinapriajina** [comment]
Awesome! Thanks Andrea.
