### ISSUE TITLE
Language buttons

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Anti-Corruption#37]
Dear all,

Could we please install the same kind of buttons we have on the ukrainian site for language switching on the front end?

Most of the content is trabnslated and uploaded. I would also like to make a tour of content we cannot edit from our side in order to provide you the relevant data if need be.

Best,

Karina

**Comment by gianpaolom** [comment]
I have added the language switcher buttons at the end of the menu.
![language-switcher](https://user-images.githubusercontent.com/8287946/33329995-92846084-d455-11e7-9e3b-20b78efdd5fb.png)
For users that are not logged in, only English is shown, until we unhide the other languages.
