### ISSUE TITLE
Title of the website needs translation

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Anti-Corruption#40]
In both versions the title of the website is in Eng, the translations are:

Security Sector Integrity:

RU
UK  ЦІЛІСНІСТЬ СЕКТОРУ БЕЗПЕКИ

I am looking into the matter now and will update this as soon as the translations are available

**Comment by karinapriajina** [comment]
still waiting for the Russian translation

**Comment by gianpaolom** [comment]
I have added the Ukranian translation. It can be translated inside `WPML -> String Translations` and looking for the english title

**Comment by karinapriajina** [comment]
thanks you. I am still waiting for confirmation on Russian but I will update myself then., Thanks for the info
