### ISSUE TITLE
Create list view for publications

### ISSUE THREAD

**Issue by adrian-activate** [ActivateMedia/DCAF-Anti-Corruption#6]

**Comment by andreafalzetti** [comment]
I have created the publications in the backend and a listing in the frontend. I've added some placeholders for the moment.

@karinapriajina Is there any metadata that you would like to add to the Publications? (eg. Author, ISBN, etc). Currently you have Publication Title, Excerpt and Thumbnail.

**Comment by karinapriajina** [comment]
Hi @andreafalzetti! Thank you. Yes Author, year of publication and languages would be cool in the lisiting...

I'm not sure what languages exactly yet...

**Comment by andreafalzetti** [comment]
What languages shall I add @karinapriajina ?

**Comment by karinapriajina** [comment]
OK we need: English, Russian, Ukrainian, French and Arabic

**Comment by karinapriajina** [comment]
we also need the same system as the ukrainian site for providing links to pdfs f rom other sources

**Comment by andreafalzetti** [comment]
From @karinapriajina:

> I have a few requests although maybe it's already on your do to list: I would like the publications to be smaller, as to fit in more publications per screen. I would als like a better listing system than "older posts"

cc @bhavesh-activatemedia

**Comment by karinapriajina** [comment]
Many thanks for this!
I can't close this issue, can someone close ti for me please? Many thanks!
