### ISSUE TITLE
Social share 

### ISSUE THREAD

**Issue by andreafalzetti** [ActivateMedia/DCAF-Anti-Corruption#7]
For Pages, Publications, etc.

**Comment by bhavesh-activatemedia** [comment]
Same as: http://ukrainesecuritysector.com/publication/

**Comment by andreafalzetti** [comment]
I added the social share icons in:

* publication listing
* single publication
* grid pages
* full width pages (topics)

**Comment by karinapriajina** [comment]
Thank you!
I can't close this issue, can someone close ti for me please? Many thanks!
