### ISSUE TITLE
Update map to show DCAF address

### ISSUE THREAD

**Issue by adrian-activate** [ActivateMedia/DCAF-Anti-Corruption#9]

**Comment by karinapriajina** [comment]
Geneva Centre for the Democratic Control of Armed Forces (DCAF)
www.dcaf.ch
NIS Programmes,
Chemin Eugène-Rigot 2E,
CH-1202 Geneva,
Switzerland

Google maps: Maison de la Paix, Geneva
https://www.google.com/maps/place/Maison+de+la+paix/@46.2207906,6.1413854,17z/data=!4m6!3m5!1s0x478c64e1ec10bcb3:0x538a2345e007d0bc!4b1!8m2!3d46.2207869!4d6.1435741?hl=en

**Comment by bhavesh-activatemedia** [comment]
To go on the footer (grey section)

**Comment by bhavesh-activatemedia** [comment]
@karinapriajina The footer has three columns on the template (https://edindemo.wordpress.com/) there is the map, about us and navigation. What would you like here?

**Comment by karinapriajina** [comment]
HI @bhavesh-activatemedia ! Well, I would suggest the map, instead of "about us" our address and maybe the dcaf logo, and navigation is fine there I think. What do you think? :)

**Comment by karinapriajina** [comment]
BTW address has changed:

Geneva Centre for the Democratic Control of Armed Forces (DCAF)
Eastern Europe, South Caucasus, Central Asia Division 
Chemin Eugène-Rigot 2E
CH-1202 Geneva
Switzerland
www.dcaf.ch

**Comment by karinapriajina** [comment]
And there's an e-mail for this website: dcaf.BI@dcaf.ch

**Comment by karinapriajina** [comment]
I have filled-in some blancs in the Footers but I don't know how to add the map or how to make the text appear properly

**Comment by andreafalzetti** [comment]
I have placed the map in the footer. @karinapriajina are you happy with it?

**Comment by karinapriajina** [comment]
YeaH! looks great
